### PR TITLE
Toggling the OSD on and off

### PR DESCRIPTION
**Pull request by Lualttt**
I use this mod to record boat racing events and it can be a bit distracting for viewers, thats why I added this feature. It has a default keybind to toggle it (O) and also a button inside the setting screen next to the fpv button.

### CODE REVIEW

**Comment by wefcdse** [comment]
thank you, i will merge it in a few hours

**Comment by wefcdse** [comment]
wait, please use datagen to generate translate files 
src/main/java/com/iung/fpv20/generate/lang
and src/main/java/com/iung/fpv20/consts

**Comment by wefcdse** [comment]
if you directly change generated json file, the changes will lose after next run of datagen

**Comment by wefcdse** [comment]
pressing f1 can hide all of the hud?

**Comment by Lualttt** [comment]
ill fix the translation files!

i know pressing f1 will hide the hud, but it will hide everything, the chat any other mods that use the hud and nametags of players which i need to see thats why i wanted to add an option for it

**Comment by wefcdse** [comment]
sorry for not uploading new version, i was too busy this month

**Comment by Lualttt** [comment]
no worries :)

**Pull request merged**
